### ISSUE TITLE
AnsibleFilterError: Version comparison: LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by NanoPish** [juju4/ansible-auditd#11]
The task `[auditd : setup rsyslog to send audisp logs to a specific target]` is failing with `AnsibleFilterError: Version comparison: LooseVersion instance has no attribute 'version'`

I have no idea what it means and I'm wondering why would it fail there as it is just a template call...

host:
```
python2.7.17
ansible 2.5.1
```

host-target:
`debian 10`

If you have an idea on what to look for to understand the error I would be very grateful.
ansible-playbook -vvv doesn't give interesting informaton just SSH EXEC some tmp file where it uploaded the script to be ran

**Comment by NanoPish** [comment]
If you can tell me your exact ansible and python version of host and target it would help also

**Comment by NanoPish** [comment]
Caused by output of rsyslogd --version different on debian system and error while parsing with awk

Fixed by PR https://github.com/juju4/ansible-auditd/pull/12

**Comment by NanoPish** [comment]
it is caused by version and not os it seems

**Comment by juju4** [comment]
normally fixed by https://github.com/juju4/ansible-auditd/commit/ee121348aec54a3c661ab8371b9a4b69e652c63d
