### ISSUE TITLE
file error rsyslog-audisp.yml

### ISSUE THREAD

**Issue by vldanch** [juju4/ansible-auditd#13]
`TASK [auditd : get rsyslog version] *****************************************************************************************************************************************************************************
fatal: [uhm01]: FAILED! => {"changed": false, "cmd": "rsyslogd -v | awk 'match($0, /rsyslogd\\s+([0-9.]+)/, a) { print a[1] }'", "delta": "0:00:00.002221", "end": "2020-06-05 11:02:56.666150", "msg": "non-zero return code", "rc": 2, "start": "2020-06-05 11:02:56.663929", "stderr": "awk: line 1: syntax error at or near ,", "stderr_lines": ["awk: line 1: syntax error at or near ,"], "stdout": "", "stdout_lines": []}
`

**Comment by vldanch** [comment]
@juju4 Fixed get rsyslog version - `- name: get rsyslog version
  shell: "rsyslogd -v | awk '/rsyslogd/ {print substr($2, 1, length($2)-1)}'"`
Add a fix, otherwise I can’t, permission denied in your project writes to me.

**Comment by juju4** [comment]
Thanks for report

This was part of change to support version extract of recent rsyslogd
https://github.com/juju4/ansible-auditd/commit/ee121348aec54a3c661ab8371b9a4b69e652c63d

what strange is in my case, above expression is working.
Can you provide tested distribution and version of rsyslog+awk?

**Comment by vldanch** [comment]
@juju4 launched on versions - `rsyslogd 8.32.0,`, `Awk 4.1.4`

**Comment by juju4** [comment]
Ubuntu 18.04? any other specific?

both expression should be working
```
$ rsyslogd -v | head -1
rsyslogd 8.32.0, compiled with:
$ rsyslogd -v | awk '/rsyslogd/ {print substr($2, 1, length($2)-1)}'
8.32.0
$ rsyslogd -v | awk 'match($0, /rsyslogd\s+([0-9.]+)/, a) { print a[1] }'
8.32.0
```

**Comment by NanoPish** [comment]
Debian GNU/Linux 10 \n \l

TASK [auditd : get rsyslog version] ************************************************************************************************************************************************************************
fatal: [IP]: FAILED! => {"changed": false, "cmd": "rsyslogd -v | awk 'match($0, /rsyslogd\\s+([0-9.]+)/, a) { print a[1] }'", "delta": "0:00:00.026935", "end": "2020-07-08 14:38:47.166582", "m
sg": "non-zero return code", "rc": 2, "start": "2020-07-08 14:38:47.139647", "stderr": "awk: line 1: syntax error at or near ,", "stderr_lines": ["awk: line 1: syntax error at or near ,"], "stdout": "", "
stdout_lines": []}                                                    
fatal: [IP]: FAILED! => {"changed": false, "cmd": "rsyslogd -v | awk 'match($0, /rsyslogd\\s+([0-9.]+)/, a) { print a[1] }'", "delta": "0:00:00.025269", "end": "2020-07-08 14:38:47.175855", "ms
g": "non-zero return code", "rc": 2, "start": "2020-07-08 14:38:47.150586", "stderr": "awk: line 1: syntax error at or near ,", "stderr_lines": ["awk: line 1: syntax error at or near ,"], "stdout": "", "s
tdout_lines": []}

**Comment by NanoPish** [comment]
`sudo rsyslogd -v | awk -F' ' '/rsyslogd/ { print $2 }'
`
8.1901.0

**Comment by juju4** [comment]
should be fixed by https://github.com/juju4/ansible-auditd/commit/c220ad1338d1d75a652e3070b57d2309d7fed3f6 and use of ansible package_facts
