### ISSUE TITLE
[FR] please add amazon linux 2 OS

### ISSUE THREAD

**Issue by Hokwang** [juju4/ansible-auditd#16]
Hi,

I need to manage AWS EC2 machines.
So please add amazon linux 2 OS in supported list.

Thanks,

**Comment by juju4** [comment]
Did you try to use this role?
Did it failed? With what error messages?

Variables inclusion is here based on OS family
https://github.com/juju4/ansible-auditd/blob/master/tasks/main.yml#L3

From what I known Amazon Linux is Redhat based.
Variable file is https://github.com/juju4/ansible-auditd/blob/master/vars/RedHat.yml

It's unlikely that there is much specific for amazon linux but if you identify an issue, please report it with more details.

Not sure what is your reference for "supported list" but if you are talking about galaxy meta platforms list, to me, it's just a base list for which there are regular tests/usage. On my side, that's limited to redhat and ubuntu base, LTS ones. But nothing prevents usage on other. I did some test on Alpine at a time but was just a point in time and did not add to list.

**Comment by juju4** [comment]
Closing as old and no updates
