### ISSUE TITLE
Loading rules fail if no LVM is active on the system

### ISSUE THREAD

**Issue by janorn** [juju4/ansible-auditd#8]
If LVM isnt installed on a machine this rule will break augenrules --load due to missing /var/lock/lvm.

```
Process: 26020 ExecStartPost=/sbin/augenrules --load (code=exited, status=1/FAILURE)
```
```
augenrules[26020]: Error sending add rule data request (No such file or directory)
augenrules[26020]: There was an error in line 12 of /etc/audit/audit.rules
```
https://github.com/juju4/ansible-auditd/blob/377b69c7ae705746b9faba5d51b3ee84a2ffc6d9/defaults/main.yml#L51

**Comment by juju4** [comment]
yes. known issue. auditd is failing on any dir or exe which does not exist...
had no time to write logic there to validate first that it exists.

but paths have been tested on redhat/centos and ubuntu.
Curious on which distribution/release are you?

**Comment by janorn** [comment]
Centos 7 without LVM....

**Comment by juju4** [comment]
Closing old issue. The normal way to deal with this is changing defaults variable.
I believe nowadays LVM to be default, at least on redhat and ubuntu LTS.

**Comment by janorn** [comment]
In a cloud environment it is not default..
